{{- if .Values.ingress.enabled -}}
{{- $fullName := include "app.fullname" . -}}
{{- $externalPort := .Values.service.externalPort -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
{{ include "app.labels" . | indent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: my-aws-ingress-class   # Ingress Class
  rules:
  {{- range .Values.ingress.hosts }}
    - http:
        paths:
        {{- range .paths }}
          - path: {{ . }}
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port: 
                  number: {{ $externalPort }}
        {{- end }}
  {{- end }}
{{- end }}