apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel
  #namespace: laravel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel-app
  template:
    metadata:
      labels:
        app: laravel-app
    spec:
      containers:
      - name: laravel-app
        image: 827539266883.dkr.ecr.ap-southeast-1.amazonaws.com/laraveldemo:latest
        imagePullPolicy: Always
        volumeMounts:
        - name: app-secret
          mountPath: "/var/www/html/secret"
          readOnly: true
        ports:
        - containerPort: 80
          name: pathao-port
          protocol: TCP
      volumes:
      - name: app-secret
        secret:
          secretName: laravel-app-secret
      imagePullSecrets:
      - name: regsecret
