apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel
  #namespace: laravel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel-app
  template:
    metadata:
      labels:
        app: laravel-app
    spec:
      containers:
      - name: laravel-app
        image: 827539266883.dkr.ecr.ap-southeast-1.amazonaws.com/laraveldemo:latest
        imagePullPolicy: Always
