apiVersion: v1
kind: Secret
metadata:
  name: laravel-app-secret
  #namespace: laravel
type: Opaque
data:
  .env: QVBQX05BTUU9TGFyYXZlbApBUFBfRU5WPWxvY2FsCkFQUF9LRVk9YmFzZTY0Ok03cTEvb3lhbUxSay9LNmtKTGRDN093QVh4RldBVFNOOVRTOW83d0o5THc9CkFQUF9ERUJVRz10cnVlCkFQUF9MT0dfTEVWRUw9ZGVidWcKQVBQX1VSTD1odHRwOi8vbG9jYWxob3N0CgpEQl9DT05ORUNUSU9OPW15c3FsCkRCX0hPU1Q9bXlzcWwKREJfUE9SVD0zMzA2CkRCX0RBVEFCQVNFPXdlYmFwcGRiCkRCX1VTRVJOQU1FPXJvb3QKREJfUEFTU1dPUkQ9ZGJwYXNzd29yZDExCgpCUk9BRENBU1RfRFJJVkVSPWxvZwpDQUNIRV9EUklWRVI9ZmlsZQpTRVNTSU9OX0RSSVZFUj1maWxlClFVRVVFX0RSSVZFUj1zeW5jCgpSRURJU19IT1NUPTEyNy4wLjAuMQpSRURJU19QQVNTV09SRD1udWxsClJFRElTX1BPUlQ9NjM3OQoKTUFJTF9EUklWRVI9c210cApNQUlMX0hPU1Q9c210cC5tYWlsdHJhcC5pbwpNQUlMX1BPUlQ9MjUyNQpNQUlMX1VTRVJOQU1FPW51bGwKTUFJTF9QQVNTV09SRD1udWxsCk1BSUxfRU5DUllQVElPTj1udWxsCgpQVVNIRVJfQVBQX0lEPQpQVVNIRVJfQVBQX0tFWT0KUFVTSEVSX0FQUF9TRUNSRVQ9Cg==
